baseurl                  = "https://example.com/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "jaffamonkey"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favico.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "©2020 jaffamonkey B.V. (KVK 71855157) Vestigingsnr: 1012 RP Amsterdam"

# Metadata for Open Graph and Twitter
    description          = "Quality engineering"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Call me Sam"

[[params.mainMenu]]
    link = "/about"
    text = "who i am"

[[params.mainMenu]]
    link = "/quality-engineering"
    text = "quality engineering"

[[params.mainMenu]]
    link = "/learning"
    text = "learn what i do"

[[params.mainMenu]]
    link = "/clients"
    text = "client history"

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[imaging]
    quality = 75