baseurl                  = "https://www.jaffamonkey.com/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "jaffamonkey"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "©2020 jaffamonkey ltd"

# Metadata for Open Graph and Twitter
    description          = "Quality engineering"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Call me Sam"

[[params.mainMenu]]
    link = "/about"
    text = "about me"

[[params.mainMenu]]
    link = "/quality-engineering"
    text = "quality engineering"

[[params.mainMenu]]
    link = "/workshops"
    text = "workshops"

[[params.mainMenu]]
    link = "/clients"
    text = "client history"

[[params.mainMenu]]
    link = "/posts"
    text = "case studies"

[[params.mainMenu]]
    link = "/app-projects"
    text = "app projects"

[imaging]
    quality = 75