baseurl                  = "https://example.com/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Call me Sam"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favico.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "©2019 jaffamonkey B.V. (KVK 71855157) Vestigingsnr: 1012 RP Amsterdam"

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Call me Sam"

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/test-engineering"
    text = "test engineering"

[[params.mainMenu]]
    link = "/quality-assurance"
    text = "quality assurance"

[[params.mainMenu]]
    link = "/training"
    text = "training"

[[params.mainMenu]]
    link = "/about"
    text = "about"

[imaging]
    quality = 75